apiVersion: v1
kind: Service
metadata:
  name: selenium-downloads-node-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    component: selenium
