apiVersion: v1
kind: Service
metadata:
  name: selenium-grid-node-service
spec:
  type: NodePort
  ports:
    - targetPort: 4444
      port: 4444
      nodePort: 30044
  selector:
    component: selenium
