apiVersion: v1
kind: Service
metadata:
  name: selenium-vnc-node-service
spec:
  type: NodePort
  ports:
    - targetPort: 5900
      port: 5900
      nodePort: 30059
  selector:
    component: selenium
